// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<28> conv2d::ap_ST_fsm_state1 = "1";
const sc_lv<28> conv2d::ap_ST_fsm_state2 = "10";
const sc_lv<28> conv2d::ap_ST_fsm_state3 = "100";
const sc_lv<28> conv2d::ap_ST_fsm_state4 = "1000";
const sc_lv<28> conv2d::ap_ST_fsm_state5 = "10000";
const sc_lv<28> conv2d::ap_ST_fsm_state6 = "100000";
const sc_lv<28> conv2d::ap_ST_fsm_state7 = "1000000";
const sc_lv<28> conv2d::ap_ST_fsm_state8 = "10000000";
const sc_lv<28> conv2d::ap_ST_fsm_state9 = "100000000";
const sc_lv<28> conv2d::ap_ST_fsm_state10 = "1000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state11 = "10000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state12 = "100000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<28> conv2d::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_C = "1100";
const sc_lv<32> conv2d::ap_const_lv32_13 = "10011";
const sc_lv<32> conv2d::ap_const_lv32_10 = "10000";
const sc_lv<32> conv2d::ap_const_lv32_17 = "10111";
const sc_lv<32> conv2d::ap_const_lv32_1 = "1";
const sc_lv<1> conv2d::ap_const_lv1_0 = "0";
const sc_lv<32> conv2d::ap_const_lv32_2 = "10";
const sc_lv<32> conv2d::ap_const_lv32_3 = "11";
const sc_lv<32> conv2d::ap_const_lv32_4 = "100";
const sc_lv<32> conv2d::ap_const_lv32_5 = "101";
const sc_lv<1> conv2d::ap_const_lv1_1 = "1";
const sc_lv<32> conv2d::ap_const_lv32_6 = "110";
const sc_lv<32> conv2d::ap_const_lv32_7 = "111";
const sc_lv<32> conv2d::ap_const_lv32_8 = "1000";
const sc_lv<32> conv2d::ap_const_lv32_B = "1011";
const sc_lv<32> conv2d::ap_const_lv32_12 = "10010";
const sc_lv<32> conv2d::ap_const_lv32_19 = "11001";
const sc_lv<32> conv2d::ap_const_lv32_1A = "11010";
const sc_lv<5> conv2d::ap_const_lv5_0 = "00000";
const sc_lv<32> conv2d::ap_const_lv32_18 = "11000";
const sc_lv<3> conv2d::ap_const_lv3_0 = "000";
const sc_lv<32> conv2d::ap_const_lv32_11 = "10001";
const sc_lv<32> conv2d::ap_const_lv32_1B = "11011";
const sc_lv<5> conv2d::ap_const_lv5_1C = "11100";
const sc_lv<5> conv2d::ap_const_lv5_1 = "1";
const sc_lv<2> conv2d::ap_const_lv2_0 = "00";
const sc_lv<3> conv2d::ap_const_lv3_5 = "101";
const sc_lv<3> conv2d::ap_const_lv3_1 = "1";
const bool conv2d::ap_const_boolean_1 = true;

conv2d::conv2d(sc_module_name name) : sc_module(name), mVcdFile(0) {
    acc_buf_U = new conv2d_acc_buf("acc_buf_U");
    acc_buf_U->clk(ap_clk);
    acc_buf_U->reset(ap_rst);
    acc_buf_U->address0(acc_buf_address0);
    acc_buf_U->ce0(acc_buf_ce0);
    acc_buf_U->we0(acc_buf_we0);
    acc_buf_U->d0(acc_buf_d0);
    acc_buf_U->q0(acc_buf_q0);
    conv2d_fadd_32ns_bkb_U1 = new conv2d_fadd_32ns_bkb<1,5,32,32,32>("conv2d_fadd_32ns_bkb_U1");
    conv2d_fadd_32ns_bkb_U1->clk(ap_clk);
    conv2d_fadd_32ns_bkb_U1->reset(ap_rst);
    conv2d_fadd_32ns_bkb_U1->din0(grp_fu_237_p0);
    conv2d_fadd_32ns_bkb_U1->din1(grp_fu_237_p1);
    conv2d_fadd_32ns_bkb_U1->ce(ap_var_for_const0);
    conv2d_fadd_32ns_bkb_U1->dout(grp_fu_237_p2);
    conv2d_fmul_32ns_cud_U2 = new conv2d_fmul_32ns_cud<1,4,32,32,32>("conv2d_fmul_32ns_cud_U2");
    conv2d_fmul_32ns_cud_U2->clk(ap_clk);
    conv2d_fmul_32ns_cud_U2->reset(ap_rst);
    conv2d_fmul_32ns_cud_U2->din0(filt_q0);
    conv2d_fmul_32ns_cud_U2->din1(in_load_reg_662);
    conv2d_fmul_32ns_cud_U2->ce(ap_var_for_const0);
    conv2d_fmul_32ns_cud_U2->dout(grp_fu_241_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_buf_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( acc_buf_addr_2_reg_634 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( sext_ln60_fu_562_p1 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( sext_ln38_fu_330_p1 );
    sensitive << ( sext_ln52_fu_442_p1 );

    SC_METHOD(thread_acc_buf_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_acc_buf_d0);
    sensitive << ( reg_257 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_acc_buf_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln37_fu_309_p2 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_add_ln36_fu_268_p2);
    sensitive << ( r_0_0_reg_147 );

    SC_METHOD(thread_add_ln37_fu_315_p2);
    sensitive << ( c_0_0_reg_158 );

    SC_METHOD(thread_add_ln38_fu_325_p2);
    sensitive << ( sub_ln38_reg_575 );
    sensitive << ( zext_ln38_2_fu_321_p1 );

    SC_METHOD(thread_add_ln43_fu_341_p2);
    sensitive << ( r1_0_0_0_reg_169 );

    SC_METHOD(thread_add_ln44_fu_383_p2);
    sensitive << ( c2_0_0_0_reg_181 );

    SC_METHOD(thread_add_ln46_fu_399_p2);
    sensitive << ( k_r_0_0_0_reg_193 );

    SC_METHOD(thread_add_ln47_fu_457_p2);
    sensitive << ( k_c_0_0_0_reg_204 );

    SC_METHOD(thread_add_ln48_1_fu_472_p2);
    sensitive << ( c2_0_0_0_reg_181 );
    sensitive << ( zext_ln47_fu_447_p1 );

    SC_METHOD(thread_add_ln48_2_fu_421_p2);
    sensitive << ( zext_ln48_fu_405_p1 );
    sensitive << ( zext_ln48_1_fu_417_p1 );

    SC_METHOD(thread_add_ln48_3_fu_467_p2);
    sensitive << ( add_ln48_2_reg_624 );
    sensitive << ( zext_ln48_2_fu_463_p1 );

    SC_METHOD(thread_add_ln48_fu_427_p2);
    sensitive << ( r1_0_0_0_reg_169 );
    sensitive << ( zext_ln46_fu_389_p1 );

    SC_METHOD(thread_add_ln52_fu_437_p2);
    sensitive << ( sub_ln52_reg_603 );
    sensitive << ( zext_ln52_2_fu_433_p1 );

    SC_METHOD(thread_add_ln58_fu_505_p2);
    sensitive << ( r3_0_0_reg_215 );

    SC_METHOD(thread_add_ln59_fu_547_p2);
    sensitive << ( c4_0_0_reg_226 );

    SC_METHOD(thread_add_ln60_fu_557_p2);
    sensitive << ( sub_ln60_reg_690 );
    sensitive << ( zext_ln60_2_fu_553_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( icmp_ln58_fu_499_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( icmp_ln58_fu_499_p2 );

    SC_METHOD(thread_filt_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln48_4_fu_490_p1 );

    SC_METHOD(thread_filt_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_237_p0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( acc_buf_load_1_reg_677 );
    sensitive << ( acc_2_0_0_fu_76 );

    SC_METHOD(thread_grp_fu_237_p1);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_s_reg_672 );
    sensitive << ( acc_2_0_0_fu_76 );

    SC_METHOD(thread_icmp_ln36_fu_262_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_0_0_reg_147 );

    SC_METHOD(thread_icmp_ln37_fu_309_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c_0_0_reg_158 );

    SC_METHOD(thread_icmp_ln43_fu_335_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( r1_0_0_0_reg_169 );

    SC_METHOD(thread_icmp_ln44_fu_377_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( c2_0_0_0_reg_181 );

    SC_METHOD(thread_icmp_ln46_fu_393_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( k_r_0_0_0_reg_193 );

    SC_METHOD(thread_icmp_ln47_fu_451_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( k_c_0_0_0_reg_204 );

    SC_METHOD(thread_icmp_ln58_fu_499_p2);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( r3_0_0_reg_215 );

    SC_METHOD(thread_icmp_ln59_fu_541_p2);
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( c4_0_0_reg_226 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln48_3_fu_485_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( sext_ln60_reg_703 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( acc_buf_q0 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_sext_ln38_fu_330_p1);
    sensitive << ( add_ln38_fu_325_p2 );

    SC_METHOD(thread_sext_ln52_fu_442_p1);
    sensitive << ( add_ln52_fu_437_p2 );

    SC_METHOD(thread_sext_ln60_fu_562_p1);
    sensitive << ( add_ln60_fu_557_p2 );

    SC_METHOD(thread_sub_ln38_fu_298_p2);
    sensitive << ( zext_ln38_fu_282_p1 );
    sensitive << ( zext_ln38_1_fu_294_p1 );

    SC_METHOD(thread_sub_ln52_fu_371_p2);
    sensitive << ( zext_ln52_fu_355_p1 );
    sensitive << ( zext_ln52_1_fu_367_p1 );

    SC_METHOD(thread_sub_ln60_fu_535_p2);
    sensitive << ( zext_ln60_fu_519_p1 );
    sensitive << ( zext_ln60_1_fu_531_p1 );

    SC_METHOD(thread_tmp_10_fu_359_p3);
    sensitive << ( r1_0_0_0_reg_169 );

    SC_METHOD(thread_tmp_11_fu_511_p3);
    sensitive << ( r3_0_0_reg_215 );

    SC_METHOD(thread_tmp_12_fu_523_p3);
    sensitive << ( r3_0_0_reg_215 );

    SC_METHOD(thread_tmp_13_fu_409_p3);
    sensitive << ( k_r_0_0_0_reg_193 );

    SC_METHOD(thread_tmp_14_fu_478_p3);
    sensitive << ( add_ln48_reg_629 );
    sensitive << ( add_ln48_1_fu_472_p2 );

    SC_METHOD(thread_tmp_7_fu_274_p3);
    sensitive << ( r_0_0_reg_147 );

    SC_METHOD(thread_tmp_8_fu_286_p3);
    sensitive << ( r_0_0_reg_147 );

    SC_METHOD(thread_tmp_9_fu_347_p3);
    sensitive << ( r1_0_0_0_reg_169 );

    SC_METHOD(thread_zext_ln38_1_fu_294_p1);
    sensitive << ( tmp_8_fu_286_p3 );

    SC_METHOD(thread_zext_ln38_2_fu_321_p1);
    sensitive << ( c_0_0_reg_158 );

    SC_METHOD(thread_zext_ln38_fu_282_p1);
    sensitive << ( tmp_7_fu_274_p3 );

    SC_METHOD(thread_zext_ln46_fu_389_p1);
    sensitive << ( k_r_0_0_0_reg_193 );

    SC_METHOD(thread_zext_ln47_fu_447_p1);
    sensitive << ( k_c_0_0_0_reg_204 );

    SC_METHOD(thread_zext_ln48_1_fu_417_p1);
    sensitive << ( tmp_13_fu_409_p3 );

    SC_METHOD(thread_zext_ln48_2_fu_463_p1);
    sensitive << ( k_c_0_0_0_reg_204 );

    SC_METHOD(thread_zext_ln48_3_fu_485_p1);
    sensitive << ( tmp_14_fu_478_p3 );

    SC_METHOD(thread_zext_ln48_4_fu_490_p1);
    sensitive << ( add_ln48_3_reg_647 );

    SC_METHOD(thread_zext_ln48_fu_405_p1);
    sensitive << ( k_r_0_0_0_reg_193 );

    SC_METHOD(thread_zext_ln52_1_fu_367_p1);
    sensitive << ( tmp_10_fu_359_p3 );

    SC_METHOD(thread_zext_ln52_2_fu_433_p1);
    sensitive << ( c2_0_0_0_reg_181 );

    SC_METHOD(thread_zext_ln52_fu_355_p1);
    sensitive << ( tmp_9_fu_347_p3 );

    SC_METHOD(thread_zext_ln60_1_fu_531_p1);
    sensitive << ( tmp_12_fu_523_p3 );

    SC_METHOD(thread_zext_ln60_2_fu_553_p1);
    sensitive << ( c4_0_0_reg_226 );

    SC_METHOD(thread_zext_ln60_fu_519_p1);
    sensitive << ( tmp_11_fu_511_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln36_fu_262_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln43_fu_335_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln46_fu_393_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln47_fu_451_p2 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( icmp_ln58_fu_499_p2 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( icmp_ln59_fu_541_p2 );
    sensitive << ( icmp_ln37_fu_309_p2 );
    sensitive << ( icmp_ln44_fu_377_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, filt_address0, "(port)filt_address0");
    sc_trace(mVcdFile, filt_ce0, "(port)filt_ce0");
    sc_trace(mVcdFile, filt_q0, "(port)filt_q0");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, grp_fu_237_p2, "grp_fu_237_p2");
    sc_trace(mVcdFile, reg_257, "reg_257");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, add_ln36_fu_268_p2, "add_ln36_fu_268_p2");
    sc_trace(mVcdFile, add_ln36_reg_570, "add_ln36_reg_570");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln38_fu_298_p2, "sub_ln38_fu_298_p2");
    sc_trace(mVcdFile, sub_ln38_reg_575, "sub_ln38_reg_575");
    sc_trace(mVcdFile, icmp_ln36_fu_262_p2, "icmp_ln36_fu_262_p2");
    sc_trace(mVcdFile, add_ln37_fu_315_p2, "add_ln37_fu_315_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln43_fu_341_p2, "add_ln43_fu_341_p2");
    sc_trace(mVcdFile, add_ln43_reg_598, "add_ln43_reg_598");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, sub_ln52_fu_371_p2, "sub_ln52_fu_371_p2");
    sc_trace(mVcdFile, sub_ln52_reg_603, "sub_ln52_reg_603");
    sc_trace(mVcdFile, icmp_ln43_fu_335_p2, "icmp_ln43_fu_335_p2");
    sc_trace(mVcdFile, add_ln44_fu_383_p2, "add_ln44_fu_383_p2");
    sc_trace(mVcdFile, add_ln44_reg_611, "add_ln44_reg_611");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, add_ln46_fu_399_p2, "add_ln46_fu_399_p2");
    sc_trace(mVcdFile, add_ln46_reg_619, "add_ln46_reg_619");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, add_ln48_2_fu_421_p2, "add_ln48_2_fu_421_p2");
    sc_trace(mVcdFile, add_ln48_2_reg_624, "add_ln48_2_reg_624");
    sc_trace(mVcdFile, icmp_ln46_fu_393_p2, "icmp_ln46_fu_393_p2");
    sc_trace(mVcdFile, add_ln48_fu_427_p2, "add_ln48_fu_427_p2");
    sc_trace(mVcdFile, add_ln48_reg_629, "add_ln48_reg_629");
    sc_trace(mVcdFile, acc_buf_addr_2_reg_634, "acc_buf_addr_2_reg_634");
    sc_trace(mVcdFile, add_ln47_fu_457_p2, "add_ln47_fu_457_p2");
    sc_trace(mVcdFile, add_ln47_reg_642, "add_ln47_reg_642");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, add_ln48_3_fu_467_p2, "add_ln48_3_fu_467_p2");
    sc_trace(mVcdFile, add_ln48_3_reg_647, "add_ln48_3_reg_647");
    sc_trace(mVcdFile, icmp_ln47_fu_451_p2, "icmp_ln47_fu_451_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, in_load_reg_662, "in_load_reg_662");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_fu_241_p2, "grp_fu_241_p2");
    sc_trace(mVcdFile, tmp_s_reg_672, "tmp_s_reg_672");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, acc_buf_q0, "acc_buf_q0");
    sc_trace(mVcdFile, acc_buf_load_1_reg_677, "acc_buf_load_1_reg_677");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, add_ln58_fu_505_p2, "add_ln58_fu_505_p2");
    sc_trace(mVcdFile, add_ln58_reg_685, "add_ln58_reg_685");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, sub_ln60_fu_535_p2, "sub_ln60_fu_535_p2");
    sc_trace(mVcdFile, sub_ln60_reg_690, "sub_ln60_reg_690");
    sc_trace(mVcdFile, icmp_ln58_fu_499_p2, "icmp_ln58_fu_499_p2");
    sc_trace(mVcdFile, add_ln59_fu_547_p2, "add_ln59_fu_547_p2");
    sc_trace(mVcdFile, add_ln59_reg_698, "add_ln59_reg_698");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, sext_ln60_fu_562_p1, "sext_ln60_fu_562_p1");
    sc_trace(mVcdFile, sext_ln60_reg_703, "sext_ln60_reg_703");
    sc_trace(mVcdFile, icmp_ln59_fu_541_p2, "icmp_ln59_fu_541_p2");
    sc_trace(mVcdFile, acc_buf_address0, "acc_buf_address0");
    sc_trace(mVcdFile, acc_buf_ce0, "acc_buf_ce0");
    sc_trace(mVcdFile, acc_buf_we0, "acc_buf_we0");
    sc_trace(mVcdFile, acc_buf_d0, "acc_buf_d0");
    sc_trace(mVcdFile, r_0_0_reg_147, "r_0_0_reg_147");
    sc_trace(mVcdFile, icmp_ln37_fu_309_p2, "icmp_ln37_fu_309_p2");
    sc_trace(mVcdFile, c_0_0_reg_158, "c_0_0_reg_158");
    sc_trace(mVcdFile, r1_0_0_0_reg_169, "r1_0_0_0_reg_169");
    sc_trace(mVcdFile, icmp_ln44_fu_377_p2, "icmp_ln44_fu_377_p2");
    sc_trace(mVcdFile, c2_0_0_0_reg_181, "c2_0_0_0_reg_181");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, k_r_0_0_0_reg_193, "k_r_0_0_0_reg_193");
    sc_trace(mVcdFile, k_c_0_0_0_reg_204, "k_c_0_0_0_reg_204");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, r3_0_0_reg_215, "r3_0_0_reg_215");
    sc_trace(mVcdFile, c4_0_0_reg_226, "c4_0_0_reg_226");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, sext_ln38_fu_330_p1, "sext_ln38_fu_330_p1");
    sc_trace(mVcdFile, sext_ln52_fu_442_p1, "sext_ln52_fu_442_p1");
    sc_trace(mVcdFile, zext_ln48_3_fu_485_p1, "zext_ln48_3_fu_485_p1");
    sc_trace(mVcdFile, zext_ln48_4_fu_490_p1, "zext_ln48_4_fu_490_p1");
    sc_trace(mVcdFile, acc_2_0_0_fu_76, "acc_2_0_0_fu_76");
    sc_trace(mVcdFile, grp_fu_237_p0, "grp_fu_237_p0");
    sc_trace(mVcdFile, grp_fu_237_p1, "grp_fu_237_p1");
    sc_trace(mVcdFile, tmp_7_fu_274_p3, "tmp_7_fu_274_p3");
    sc_trace(mVcdFile, tmp_8_fu_286_p3, "tmp_8_fu_286_p3");
    sc_trace(mVcdFile, zext_ln38_fu_282_p1, "zext_ln38_fu_282_p1");
    sc_trace(mVcdFile, zext_ln38_1_fu_294_p1, "zext_ln38_1_fu_294_p1");
    sc_trace(mVcdFile, zext_ln38_2_fu_321_p1, "zext_ln38_2_fu_321_p1");
    sc_trace(mVcdFile, add_ln38_fu_325_p2, "add_ln38_fu_325_p2");
    sc_trace(mVcdFile, tmp_9_fu_347_p3, "tmp_9_fu_347_p3");
    sc_trace(mVcdFile, tmp_10_fu_359_p3, "tmp_10_fu_359_p3");
    sc_trace(mVcdFile, zext_ln52_fu_355_p1, "zext_ln52_fu_355_p1");
    sc_trace(mVcdFile, zext_ln52_1_fu_367_p1, "zext_ln52_1_fu_367_p1");
    sc_trace(mVcdFile, tmp_13_fu_409_p3, "tmp_13_fu_409_p3");
    sc_trace(mVcdFile, zext_ln48_fu_405_p1, "zext_ln48_fu_405_p1");
    sc_trace(mVcdFile, zext_ln48_1_fu_417_p1, "zext_ln48_1_fu_417_p1");
    sc_trace(mVcdFile, zext_ln46_fu_389_p1, "zext_ln46_fu_389_p1");
    sc_trace(mVcdFile, zext_ln52_2_fu_433_p1, "zext_ln52_2_fu_433_p1");
    sc_trace(mVcdFile, add_ln52_fu_437_p2, "add_ln52_fu_437_p2");
    sc_trace(mVcdFile, zext_ln48_2_fu_463_p1, "zext_ln48_2_fu_463_p1");
    sc_trace(mVcdFile, zext_ln47_fu_447_p1, "zext_ln47_fu_447_p1");
    sc_trace(mVcdFile, add_ln48_1_fu_472_p2, "add_ln48_1_fu_472_p2");
    sc_trace(mVcdFile, tmp_14_fu_478_p3, "tmp_14_fu_478_p3");
    sc_trace(mVcdFile, tmp_11_fu_511_p3, "tmp_11_fu_511_p3");
    sc_trace(mVcdFile, tmp_12_fu_523_p3, "tmp_12_fu_523_p3");
    sc_trace(mVcdFile, zext_ln60_fu_519_p1, "zext_ln60_fu_519_p1");
    sc_trace(mVcdFile, zext_ln60_1_fu_531_p1, "zext_ln60_1_fu_531_p1");
    sc_trace(mVcdFile, zext_ln60_2_fu_553_p1, "zext_ln60_2_fu_553_p1");
    sc_trace(mVcdFile, add_ln60_fu_557_p2, "add_ln60_fu_557_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("conv2d.hdltvin.dat");
    mHdltvoutHandle.open("conv2d.hdltvout.dat");
}

conv2d::~conv2d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete acc_buf_U;
    delete conv2d_fadd_32ns_bkb_U1;
    delete conv2d_fmul_32ns_cud_U2;
}

void conv2d::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv2d::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        acc_2_0_0_fu_76 = reg_257.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln36_fu_262_p2.read(), ap_const_lv1_1))) {
        acc_2_0_0_fu_76 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        c2_0_0_0_reg_181 = add_ln44_reg_611.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_335_p2.read()))) {
        c2_0_0_0_reg_181 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        c4_0_0_reg_226 = add_ln59_reg_698.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln58_fu_499_p2.read()))) {
        c4_0_0_reg_226 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln37_fu_309_p2.read()))) {
        c_0_0_reg_158 = add_ln37_fu_315_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln36_fu_262_p2.read(), ap_const_lv1_0))) {
        c_0_0_reg_158 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        k_c_0_0_0_reg_204 = add_ln47_reg_642.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln46_fu_393_p2.read()))) {
        k_c_0_0_0_reg_204 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln47_fu_451_p2.read()))) {
        k_r_0_0_0_reg_193 = add_ln46_reg_619.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln44_fu_377_p2.read()))) {
        k_r_0_0_0_reg_193 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln44_fu_377_p2.read()))) {
        r1_0_0_0_reg_169 = add_ln43_reg_598.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln36_fu_262_p2.read(), ap_const_lv1_1))) {
        r1_0_0_0_reg_169 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln43_fu_335_p2.read(), ap_const_lv1_1))) {
        r3_0_0_reg_215 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln59_fu_541_p2.read()))) {
        r3_0_0_reg_215 = add_ln58_reg_685.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln37_fu_309_p2.read()))) {
        r_0_0_reg_147 = add_ln36_reg_570.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_0_0_reg_147 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln46_fu_393_p2.read(), ap_const_lv1_1))) {
        acc_buf_addr_2_reg_634 =  (sc_lv<10>) (sext_ln52_fu_442_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        acc_buf_load_1_reg_677 = acc_buf_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln36_reg_570 = add_ln36_fu_268_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln43_reg_598 = add_ln43_fu_341_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln44_reg_611 = add_ln44_fu_383_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln46_reg_619 = add_ln46_fu_399_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        add_ln47_reg_642 = add_ln47_fu_457_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln46_fu_393_p2.read()))) {
        add_ln48_2_reg_624 = add_ln48_2_fu_421_p2.read();
        add_ln48_reg_629 = add_ln48_fu_427_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln47_fu_451_p2.read()))) {
        add_ln48_3_reg_647 = add_ln48_3_fu_467_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        add_ln58_reg_685 = add_ln58_fu_505_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        add_ln59_reg_698 = add_ln59_fu_547_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        in_load_reg_662 = in_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        reg_257 = grp_fu_237_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln59_fu_541_p2.read()))) {
        sext_ln60_reg_703 = sext_ln60_fu_562_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln36_fu_262_p2.read(), ap_const_lv1_0))) {
        sub_ln38_reg_575 = sub_ln38_fu_298_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln43_fu_335_p2.read()))) {
        sub_ln52_reg_603 = sub_ln52_fu_371_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln58_fu_499_p2.read()))) {
        sub_ln60_reg_690 = sub_ln60_fu_535_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_s_reg_672 = grp_fu_241_p2.read();
    }
}

void conv2d::thread_acc_buf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        acc_buf_address0 =  (sc_lv<10>) (sext_ln60_fu_562_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        acc_buf_address0 = acc_buf_addr_2_reg_634.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        acc_buf_address0 =  (sc_lv<10>) (sext_ln52_fu_442_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        acc_buf_address0 =  (sc_lv<10>) (sext_ln38_fu_330_p1.read());
    } else {
        acc_buf_address0 = "XXXXXXXXXX";
    }
}

void conv2d::thread_acc_buf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        acc_buf_ce0 = ap_const_logic_1;
    } else {
        acc_buf_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_acc_buf_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        acc_buf_d0 = reg_257.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        acc_buf_d0 = ap_const_lv32_0;
    } else {
        acc_buf_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void conv2d::thread_acc_buf_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln37_fu_309_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        acc_buf_we0 = ap_const_logic_1;
    } else {
        acc_buf_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_add_ln36_fu_268_p2() {
    add_ln36_fu_268_p2 = (!r_0_0_reg_147.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(r_0_0_reg_147.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_add_ln37_fu_315_p2() {
    add_ln37_fu_315_p2 = (!c_0_0_reg_158.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c_0_0_reg_158.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_add_ln38_fu_325_p2() {
    add_ln38_fu_325_p2 = (!sub_ln38_reg_575.read().is_01() || !zext_ln38_2_fu_321_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(sub_ln38_reg_575.read()) + sc_biguint<11>(zext_ln38_2_fu_321_p1.read()));
}

void conv2d::thread_add_ln43_fu_341_p2() {
    add_ln43_fu_341_p2 = (!r1_0_0_0_reg_169.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(r1_0_0_0_reg_169.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_add_ln44_fu_383_p2() {
    add_ln44_fu_383_p2 = (!c2_0_0_0_reg_181.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c2_0_0_0_reg_181.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_add_ln46_fu_399_p2() {
    add_ln46_fu_399_p2 = (!k_r_0_0_0_reg_193.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_r_0_0_0_reg_193.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2d::thread_add_ln47_fu_457_p2() {
    add_ln47_fu_457_p2 = (!k_c_0_0_0_reg_204.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_c_0_0_0_reg_204.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2d::thread_add_ln48_1_fu_472_p2() {
    add_ln48_1_fu_472_p2 = (!zext_ln47_fu_447_p1.read().is_01() || !c2_0_0_0_reg_181.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln47_fu_447_p1.read()) + sc_biguint<5>(c2_0_0_0_reg_181.read()));
}

void conv2d::thread_add_ln48_2_fu_421_p2() {
    add_ln48_2_fu_421_p2 = (!zext_ln48_fu_405_p1.read().is_01() || !zext_ln48_1_fu_417_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln48_fu_405_p1.read()) + sc_biguint<6>(zext_ln48_1_fu_417_p1.read()));
}

void conv2d::thread_add_ln48_3_fu_467_p2() {
    add_ln48_3_fu_467_p2 = (!add_ln48_2_reg_624.read().is_01() || !zext_ln48_2_fu_463_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(add_ln48_2_reg_624.read()) + sc_biguint<6>(zext_ln48_2_fu_463_p1.read()));
}

void conv2d::thread_add_ln48_fu_427_p2() {
    add_ln48_fu_427_p2 = (!zext_ln46_fu_389_p1.read().is_01() || !r1_0_0_0_reg_169.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln46_fu_389_p1.read()) + sc_biguint<5>(r1_0_0_0_reg_169.read()));
}

void conv2d::thread_add_ln52_fu_437_p2() {
    add_ln52_fu_437_p2 = (!sub_ln52_reg_603.read().is_01() || !zext_ln52_2_fu_433_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(sub_ln52_reg_603.read()) + sc_biguint<11>(zext_ln52_2_fu_433_p1.read()));
}

void conv2d::thread_add_ln58_fu_505_p2() {
    add_ln58_fu_505_p2 = (!r3_0_0_reg_215.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(r3_0_0_reg_215.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_add_ln59_fu_547_p2() {
    add_ln59_fu_547_p2 = (!c4_0_0_reg_226.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c4_0_0_reg_226.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_add_ln60_fu_557_p2() {
    add_ln60_fu_557_p2 = (!sub_ln60_reg_690.read().is_01() || !zext_ln60_2_fu_553_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(sub_ln60_reg_690.read()) + sc_biguint<11>(zext_ln60_2_fu_553_p1.read()));
}

void conv2d::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2d::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv2d::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv2d::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void conv2d::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv2d::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void conv2d::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2d::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void conv2d::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void conv2d::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void conv2d::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void conv2d::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void conv2d::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void conv2d::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2d::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2d::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv2d::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv2d::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv2d::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv2d::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv2d::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_499_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2d::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2d::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_499_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2d::thread_filt_address0() {
    filt_address0 =  (sc_lv<5>) (zext_ln48_4_fu_490_p1.read());
}

void conv2d::thread_filt_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        filt_ce0 = ap_const_logic_1;
    } else {
        filt_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_grp_fu_237_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_237_p0 = acc_buf_load_1_reg_677.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_237_p0 = acc_2_0_0_fu_76.read();
    } else {
        grp_fu_237_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void conv2d::thread_grp_fu_237_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        grp_fu_237_p1 = acc_2_0_0_fu_76.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_237_p1 = tmp_s_reg_672.read();
    } else {
        grp_fu_237_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void conv2d::thread_icmp_ln36_fu_262_p2() {
    icmp_ln36_fu_262_p2 = (!r_0_0_reg_147.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(r_0_0_reg_147.read() == ap_const_lv5_1C);
}

void conv2d::thread_icmp_ln37_fu_309_p2() {
    icmp_ln37_fu_309_p2 = (!c_0_0_reg_158.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(c_0_0_reg_158.read() == ap_const_lv5_1C);
}

void conv2d::thread_icmp_ln43_fu_335_p2() {
    icmp_ln43_fu_335_p2 = (!r1_0_0_0_reg_169.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(r1_0_0_0_reg_169.read() == ap_const_lv5_1C);
}

void conv2d::thread_icmp_ln44_fu_377_p2() {
    icmp_ln44_fu_377_p2 = (!c2_0_0_0_reg_181.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(c2_0_0_0_reg_181.read() == ap_const_lv5_1C);
}

void conv2d::thread_icmp_ln46_fu_393_p2() {
    icmp_ln46_fu_393_p2 = (!k_r_0_0_0_reg_193.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(k_r_0_0_0_reg_193.read() == ap_const_lv3_5);
}

void conv2d::thread_icmp_ln47_fu_451_p2() {
    icmp_ln47_fu_451_p2 = (!k_c_0_0_0_reg_204.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(k_c_0_0_0_reg_204.read() == ap_const_lv3_5);
}

void conv2d::thread_icmp_ln58_fu_499_p2() {
    icmp_ln58_fu_499_p2 = (!r3_0_0_reg_215.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(r3_0_0_reg_215.read() == ap_const_lv5_1C);
}

void conv2d::thread_icmp_ln59_fu_541_p2() {
    icmp_ln59_fu_541_p2 = (!c4_0_0_reg_226.read().is_01() || !ap_const_lv5_1C.is_01())? sc_lv<1>(): sc_lv<1>(c4_0_0_reg_226.read() == ap_const_lv5_1C);
}

void conv2d::thread_in_r_address0() {
    in_r_address0 =  (sc_lv<10>) (zext_ln48_3_fu_485_p1.read());
}

void conv2d::thread_in_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<10>) (sext_ln60_reg_703.read());
}

void conv2d::thread_out_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_out_r_d0() {
    out_r_d0 = acc_buf_q0.read();
}

void conv2d::thread_out_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_sext_ln38_fu_330_p1() {
    sext_ln38_fu_330_p1 = esl_sext<64,11>(add_ln38_fu_325_p2.read());
}

void conv2d::thread_sext_ln52_fu_442_p1() {
    sext_ln52_fu_442_p1 = esl_sext<64,11>(add_ln52_fu_437_p2.read());
}

void conv2d::thread_sext_ln60_fu_562_p1() {
    sext_ln60_fu_562_p1 = esl_sext<64,11>(add_ln60_fu_557_p2.read());
}

void conv2d::thread_sub_ln38_fu_298_p2() {
    sub_ln38_fu_298_p2 = (!zext_ln38_fu_282_p1.read().is_01() || !zext_ln38_1_fu_294_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln38_fu_282_p1.read()) - sc_biguint<11>(zext_ln38_1_fu_294_p1.read()));
}

void conv2d::thread_sub_ln52_fu_371_p2() {
    sub_ln52_fu_371_p2 = (!zext_ln52_fu_355_p1.read().is_01() || !zext_ln52_1_fu_367_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln52_fu_355_p1.read()) - sc_biguint<11>(zext_ln52_1_fu_367_p1.read()));
}

void conv2d::thread_sub_ln60_fu_535_p2() {
    sub_ln60_fu_535_p2 = (!zext_ln60_fu_519_p1.read().is_01() || !zext_ln60_1_fu_531_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln60_fu_519_p1.read()) - sc_biguint<11>(zext_ln60_1_fu_531_p1.read()));
}

void conv2d::thread_tmp_10_fu_359_p3() {
    tmp_10_fu_359_p3 = esl_concat<5,2>(r1_0_0_0_reg_169.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_11_fu_511_p3() {
    tmp_11_fu_511_p3 = esl_concat<5,5>(r3_0_0_reg_215.read(), ap_const_lv5_0);
}

void conv2d::thread_tmp_12_fu_523_p3() {
    tmp_12_fu_523_p3 = esl_concat<5,2>(r3_0_0_reg_215.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_13_fu_409_p3() {
    tmp_13_fu_409_p3 = esl_concat<3,2>(k_r_0_0_0_reg_193.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_14_fu_478_p3() {
    tmp_14_fu_478_p3 = esl_concat<5,5>(add_ln48_reg_629.read(), add_ln48_1_fu_472_p2.read());
}

void conv2d::thread_tmp_7_fu_274_p3() {
    tmp_7_fu_274_p3 = esl_concat<5,5>(r_0_0_reg_147.read(), ap_const_lv5_0);
}

void conv2d::thread_tmp_8_fu_286_p3() {
    tmp_8_fu_286_p3 = esl_concat<5,2>(r_0_0_reg_147.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_9_fu_347_p3() {
    tmp_9_fu_347_p3 = esl_concat<5,5>(r1_0_0_0_reg_169.read(), ap_const_lv5_0);
}

void conv2d::thread_zext_ln38_1_fu_294_p1() {
    zext_ln38_1_fu_294_p1 = esl_zext<11,7>(tmp_8_fu_286_p3.read());
}

void conv2d::thread_zext_ln38_2_fu_321_p1() {
    zext_ln38_2_fu_321_p1 = esl_zext<11,5>(c_0_0_reg_158.read());
}

void conv2d::thread_zext_ln38_fu_282_p1() {
    zext_ln38_fu_282_p1 = esl_zext<11,10>(tmp_7_fu_274_p3.read());
}

void conv2d::thread_zext_ln46_fu_389_p1() {
    zext_ln46_fu_389_p1 = esl_zext<5,3>(k_r_0_0_0_reg_193.read());
}

void conv2d::thread_zext_ln47_fu_447_p1() {
    zext_ln47_fu_447_p1 = esl_zext<5,3>(k_c_0_0_0_reg_204.read());
}

void conv2d::thread_zext_ln48_1_fu_417_p1() {
    zext_ln48_1_fu_417_p1 = esl_zext<6,5>(tmp_13_fu_409_p3.read());
}

void conv2d::thread_zext_ln48_2_fu_463_p1() {
    zext_ln48_2_fu_463_p1 = esl_zext<6,3>(k_c_0_0_0_reg_204.read());
}

void conv2d::thread_zext_ln48_3_fu_485_p1() {
    zext_ln48_3_fu_485_p1 = esl_zext<64,10>(tmp_14_fu_478_p3.read());
}

void conv2d::thread_zext_ln48_4_fu_490_p1() {
    zext_ln48_4_fu_490_p1 = esl_zext<64,6>(add_ln48_3_reg_647.read());
}

void conv2d::thread_zext_ln48_fu_405_p1() {
    zext_ln48_fu_405_p1 = esl_zext<6,3>(k_r_0_0_0_reg_193.read());
}

void conv2d::thread_zext_ln52_1_fu_367_p1() {
    zext_ln52_1_fu_367_p1 = esl_zext<11,7>(tmp_10_fu_359_p3.read());
}

void conv2d::thread_zext_ln52_2_fu_433_p1() {
    zext_ln52_2_fu_433_p1 = esl_zext<11,5>(c2_0_0_0_reg_181.read());
}

void conv2d::thread_zext_ln52_fu_355_p1() {
    zext_ln52_fu_355_p1 = esl_zext<11,10>(tmp_9_fu_347_p3.read());
}

void conv2d::thread_zext_ln60_1_fu_531_p1() {
    zext_ln60_1_fu_531_p1 = esl_zext<11,7>(tmp_12_fu_523_p3.read());
}

void conv2d::thread_zext_ln60_2_fu_553_p1() {
    zext_ln60_2_fu_553_p1 = esl_zext<11,5>(c4_0_0_reg_226.read());
}

void conv2d::thread_zext_ln60_fu_519_p1() {
    zext_ln60_fu_519_p1 = esl_zext<11,10>(tmp_11_fu_511_p3.read());
}

void conv2d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln36_fu_262_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln37_fu_309_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln43_fu_335_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state26;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln44_fu_377_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln46_fu_393_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln47_fu_451_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 33554432 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_499_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state27;
            }
            break;
        case 67108864 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln59_fu_541_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state26;
            } else {
                ap_NS_fsm = ap_ST_fsm_state28;
            }
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<28>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void conv2d::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_address0\" :  \"" << in_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_ce0\" :  \"" << in_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_q0\" :  \"" << in_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"filt_address0\" :  \"" << filt_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"filt_ce0\" :  \"" << filt_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"filt_q0\" :  \"" << filt_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_address0\" :  \"" << out_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_ce0\" :  \"" << out_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_we0\" :  \"" << out_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_d0\" :  \"" << out_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

