// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv2d_HH_
#define _conv2d_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "conv2d_fadd_32ns_bkb.h"
#include "conv2d_fmul_32ns_cud.h"
#include "conv2d_acc_buf.h"

namespace ap_rtl {

struct conv2d : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > in_r_address0;
    sc_out< sc_logic > in_r_ce0;
    sc_in< sc_lv<32> > in_r_q0;
    sc_out< sc_lv<5> > filt_address0;
    sc_out< sc_logic > filt_ce0;
    sc_in< sc_lv<32> > filt_q0;
    sc_out< sc_lv<10> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<32> > out_r_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    conv2d(sc_module_name name);
    SC_HAS_PROCESS(conv2d);

    ~conv2d();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    conv2d_acc_buf* acc_buf_U;
    conv2d_fadd_32ns_bkb<1,5,32,32,32>* conv2d_fadd_32ns_bkb_U1;
    conv2d_fmul_32ns_cud<1,4,32,32,32>* conv2d_fmul_32ns_cud_U2;
    sc_signal< sc_lv<28> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_lv<32> > grp_fu_237_p2;
    sc_signal< sc_lv<32> > reg_257;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<5> > add_ln36_fu_268_p2;
    sc_signal< sc_lv<5> > add_ln36_reg_570;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<11> > sub_ln38_fu_298_p2;
    sc_signal< sc_lv<11> > sub_ln38_reg_575;
    sc_signal< sc_lv<1> > icmp_ln36_fu_262_p2;
    sc_signal< sc_lv<5> > add_ln37_fu_315_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > add_ln43_fu_341_p2;
    sc_signal< sc_lv<5> > add_ln43_reg_598;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<11> > sub_ln52_fu_371_p2;
    sc_signal< sc_lv<11> > sub_ln52_reg_603;
    sc_signal< sc_lv<1> > icmp_ln43_fu_335_p2;
    sc_signal< sc_lv<5> > add_ln44_fu_383_p2;
    sc_signal< sc_lv<5> > add_ln44_reg_611;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<3> > add_ln46_fu_399_p2;
    sc_signal< sc_lv<3> > add_ln46_reg_619;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<6> > add_ln48_2_fu_421_p2;
    sc_signal< sc_lv<6> > add_ln48_2_reg_624;
    sc_signal< sc_lv<1> > icmp_ln46_fu_393_p2;
    sc_signal< sc_lv<5> > add_ln48_fu_427_p2;
    sc_signal< sc_lv<5> > add_ln48_reg_629;
    sc_signal< sc_lv<10> > acc_buf_addr_2_reg_634;
    sc_signal< sc_lv<3> > add_ln47_fu_457_p2;
    sc_signal< sc_lv<3> > add_ln47_reg_642;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<6> > add_ln48_3_fu_467_p2;
    sc_signal< sc_lv<6> > add_ln48_3_reg_647;
    sc_signal< sc_lv<1> > icmp_ln47_fu_451_p2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > in_load_reg_662;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > grp_fu_241_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_672;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > acc_buf_q0;
    sc_signal< sc_lv<32> > acc_buf_load_1_reg_677;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<5> > add_ln58_fu_505_p2;
    sc_signal< sc_lv<5> > add_ln58_reg_685;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<11> > sub_ln60_fu_535_p2;
    sc_signal< sc_lv<11> > sub_ln60_reg_690;
    sc_signal< sc_lv<1> > icmp_ln58_fu_499_p2;
    sc_signal< sc_lv<5> > add_ln59_fu_547_p2;
    sc_signal< sc_lv<5> > add_ln59_reg_698;
    sc_signal< sc_logic > ap_CS_fsm_state27;
    sc_signal< sc_lv<64> > sext_ln60_fu_562_p1;
    sc_signal< sc_lv<64> > sext_ln60_reg_703;
    sc_signal< sc_lv<1> > icmp_ln59_fu_541_p2;
    sc_signal< sc_lv<10> > acc_buf_address0;
    sc_signal< sc_logic > acc_buf_ce0;
    sc_signal< sc_logic > acc_buf_we0;
    sc_signal< sc_lv<32> > acc_buf_d0;
    sc_signal< sc_lv<5> > r_0_0_reg_147;
    sc_signal< sc_lv<1> > icmp_ln37_fu_309_p2;
    sc_signal< sc_lv<5> > c_0_0_reg_158;
    sc_signal< sc_lv<5> > r1_0_0_0_reg_169;
    sc_signal< sc_lv<1> > icmp_ln44_fu_377_p2;
    sc_signal< sc_lv<5> > c2_0_0_0_reg_181;
    sc_signal< sc_logic > ap_CS_fsm_state25;
    sc_signal< sc_lv<3> > k_r_0_0_0_reg_193;
    sc_signal< sc_lv<3> > k_c_0_0_0_reg_204;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<5> > r3_0_0_reg_215;
    sc_signal< sc_lv<5> > c4_0_0_reg_226;
    sc_signal< sc_logic > ap_CS_fsm_state28;
    sc_signal< sc_lv<64> > sext_ln38_fu_330_p1;
    sc_signal< sc_lv<64> > sext_ln52_fu_442_p1;
    sc_signal< sc_lv<64> > zext_ln48_3_fu_485_p1;
    sc_signal< sc_lv<64> > zext_ln48_4_fu_490_p1;
    sc_signal< sc_lv<32> > acc_2_0_0_fu_76;
    sc_signal< sc_lv<32> > grp_fu_237_p0;
    sc_signal< sc_lv<32> > grp_fu_237_p1;
    sc_signal< sc_lv<10> > tmp_7_fu_274_p3;
    sc_signal< sc_lv<7> > tmp_8_fu_286_p3;
    sc_signal< sc_lv<11> > zext_ln38_fu_282_p1;
    sc_signal< sc_lv<11> > zext_ln38_1_fu_294_p1;
    sc_signal< sc_lv<11> > zext_ln38_2_fu_321_p1;
    sc_signal< sc_lv<11> > add_ln38_fu_325_p2;
    sc_signal< sc_lv<10> > tmp_9_fu_347_p3;
    sc_signal< sc_lv<7> > tmp_10_fu_359_p3;
    sc_signal< sc_lv<11> > zext_ln52_fu_355_p1;
    sc_signal< sc_lv<11> > zext_ln52_1_fu_367_p1;
    sc_signal< sc_lv<5> > tmp_13_fu_409_p3;
    sc_signal< sc_lv<6> > zext_ln48_fu_405_p1;
    sc_signal< sc_lv<6> > zext_ln48_1_fu_417_p1;
    sc_signal< sc_lv<5> > zext_ln46_fu_389_p1;
    sc_signal< sc_lv<11> > zext_ln52_2_fu_433_p1;
    sc_signal< sc_lv<11> > add_ln52_fu_437_p2;
    sc_signal< sc_lv<6> > zext_ln48_2_fu_463_p1;
    sc_signal< sc_lv<5> > zext_ln47_fu_447_p1;
    sc_signal< sc_lv<5> > add_ln48_1_fu_472_p2;
    sc_signal< sc_lv<10> > tmp_14_fu_478_p3;
    sc_signal< sc_lv<10> > tmp_11_fu_511_p3;
    sc_signal< sc_lv<7> > tmp_12_fu_523_p3;
    sc_signal< sc_lv<11> > zext_ln60_fu_519_p1;
    sc_signal< sc_lv<11> > zext_ln60_1_fu_531_p1;
    sc_signal< sc_lv<11> > zext_ln60_2_fu_553_p1;
    sc_signal< sc_lv<11> > add_ln60_fu_557_p2;
    sc_signal< sc_lv<28> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<28> ap_ST_fsm_state1;
    static const sc_lv<28> ap_ST_fsm_state2;
    static const sc_lv<28> ap_ST_fsm_state3;
    static const sc_lv<28> ap_ST_fsm_state4;
    static const sc_lv<28> ap_ST_fsm_state5;
    static const sc_lv<28> ap_ST_fsm_state6;
    static const sc_lv<28> ap_ST_fsm_state7;
    static const sc_lv<28> ap_ST_fsm_state8;
    static const sc_lv<28> ap_ST_fsm_state9;
    static const sc_lv<28> ap_ST_fsm_state10;
    static const sc_lv<28> ap_ST_fsm_state11;
    static const sc_lv<28> ap_ST_fsm_state12;
    static const sc_lv<28> ap_ST_fsm_state13;
    static const sc_lv<28> ap_ST_fsm_state14;
    static const sc_lv<28> ap_ST_fsm_state15;
    static const sc_lv<28> ap_ST_fsm_state16;
    static const sc_lv<28> ap_ST_fsm_state17;
    static const sc_lv<28> ap_ST_fsm_state18;
    static const sc_lv<28> ap_ST_fsm_state19;
    static const sc_lv<28> ap_ST_fsm_state20;
    static const sc_lv<28> ap_ST_fsm_state21;
    static const sc_lv<28> ap_ST_fsm_state22;
    static const sc_lv<28> ap_ST_fsm_state23;
    static const sc_lv<28> ap_ST_fsm_state24;
    static const sc_lv<28> ap_ST_fsm_state25;
    static const sc_lv<28> ap_ST_fsm_state26;
    static const sc_lv<28> ap_ST_fsm_state27;
    static const sc_lv<28> ap_ST_fsm_state28;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<5> ap_const_lv5_1C;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_acc_buf_address0();
    void thread_acc_buf_ce0();
    void thread_acc_buf_d0();
    void thread_acc_buf_we0();
    void thread_add_ln36_fu_268_p2();
    void thread_add_ln37_fu_315_p2();
    void thread_add_ln38_fu_325_p2();
    void thread_add_ln43_fu_341_p2();
    void thread_add_ln44_fu_383_p2();
    void thread_add_ln46_fu_399_p2();
    void thread_add_ln47_fu_457_p2();
    void thread_add_ln48_1_fu_472_p2();
    void thread_add_ln48_2_fu_421_p2();
    void thread_add_ln48_3_fu_467_p2();
    void thread_add_ln48_fu_427_p2();
    void thread_add_ln52_fu_437_p2();
    void thread_add_ln58_fu_505_p2();
    void thread_add_ln59_fu_547_p2();
    void thread_add_ln60_fu_557_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state27();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_filt_address0();
    void thread_filt_ce0();
    void thread_grp_fu_237_p0();
    void thread_grp_fu_237_p1();
    void thread_icmp_ln36_fu_262_p2();
    void thread_icmp_ln37_fu_309_p2();
    void thread_icmp_ln43_fu_335_p2();
    void thread_icmp_ln44_fu_377_p2();
    void thread_icmp_ln46_fu_393_p2();
    void thread_icmp_ln47_fu_451_p2();
    void thread_icmp_ln58_fu_499_p2();
    void thread_icmp_ln59_fu_541_p2();
    void thread_in_r_address0();
    void thread_in_r_ce0();
    void thread_out_r_address0();
    void thread_out_r_ce0();
    void thread_out_r_d0();
    void thread_out_r_we0();
    void thread_sext_ln38_fu_330_p1();
    void thread_sext_ln52_fu_442_p1();
    void thread_sext_ln60_fu_562_p1();
    void thread_sub_ln38_fu_298_p2();
    void thread_sub_ln52_fu_371_p2();
    void thread_sub_ln60_fu_535_p2();
    void thread_tmp_10_fu_359_p3();
    void thread_tmp_11_fu_511_p3();
    void thread_tmp_12_fu_523_p3();
    void thread_tmp_13_fu_409_p3();
    void thread_tmp_14_fu_478_p3();
    void thread_tmp_7_fu_274_p3();
    void thread_tmp_8_fu_286_p3();
    void thread_tmp_9_fu_347_p3();
    void thread_zext_ln38_1_fu_294_p1();
    void thread_zext_ln38_2_fu_321_p1();
    void thread_zext_ln38_fu_282_p1();
    void thread_zext_ln46_fu_389_p1();
    void thread_zext_ln47_fu_447_p1();
    void thread_zext_ln48_1_fu_417_p1();
    void thread_zext_ln48_2_fu_463_p1();
    void thread_zext_ln48_3_fu_485_p1();
    void thread_zext_ln48_4_fu_490_p1();
    void thread_zext_ln48_fu_405_p1();
    void thread_zext_ln52_1_fu_367_p1();
    void thread_zext_ln52_2_fu_433_p1();
    void thread_zext_ln52_fu_355_p1();
    void thread_zext_ln60_1_fu_531_p1();
    void thread_zext_ln60_2_fu_553_p1();
    void thread_zext_ln60_fu_519_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
